CREATE DATABASE ECOMMERCE;

USE ECOMMERCE;
DROP TABLE PRODUCTS;
CREATE TABLE PRODUCTS(
	PRODUCT_ID INT AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(64) NOT NULL,
    SUBCATEGORY_ID INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (SUBCATEGORY_ID) REFERENCES SUBCATEGORY(SUBCATEGORY_ID)
);

CREATE TABLE CATEGORY(
	CATEGORY_ID INT AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(64) NOT NULL,
    PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE SUBCATEGORY(
	SUBCATEGORY_ID INT AUTO_INCREMENT,
    SUBCATEGORY_NAME VARCHAR(64) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    PRIMARY KEY (SUBCATEGORY_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE TABLE ORDERS (
	ORDER_ID INT AUTO_INCREMENT,
    ORDER_NAME VARCHAR(64) NOT NULL,
    PRIMARY KEY (ORDER_ID)
);